[package]
name = "e3"
version = "0.1.0"
authors = ["niv"]
edition = "2018"

include = ["*.rs"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]